### ISSUE TITLE
GPS logging incorrectly

### ISSUE THREAD

**Issue by seanbonner** [Safecast/bGeigieMini#16]
As noted in this issue:
https://github.com/Safecast/safecastapi/issues/147

Seems that the bGeigie Nano firmware is reporting incorrect numbers of satellites. Needs to be corrected so that we can use that number for sanity checks.

**Comment by fakufaku** [comment]
Hi @seanbonner ,

This is not the repo for the bGeigieNano. I think it is this [one](https://github.com/Safecast/bGeigieNanoKit).
